#!/bin/sh
pypath="${PWD}"
pyscript="./lalapps_nest2pos.py"
PYTHONPATH=`echo "${PYTHONPATH}" | /bin/sed -e "s|${pypath}:||g;"`
PYTHONPATH="${pypath}:${PYTHONPATH}"
export PYTHONPATH
exec /usr/bin/python "${pyscript}" "$@"
exit 1
